version: '3'

services:
  api:
    build: .
    command:
      - uvicorn
      - main:app
      - --host=0.0.0.0
      - --port=4567

    ports:
      - "4567:4567"

    volumes:
      - .:/code

    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:


